### ISSUE TITLE
Number of clients

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodlebox#107]
Hi Nicolas,
a friend in my Moodletreff group found that he can‘t connect more than 15 clients to the MoodleBox 2.5.0. Using the Version 2.4.1 there werde no Problems with 25 clients. 

How can I check my MoodleBox? Where does the MoodleBox save its client data? Is the client data saved in RAM or is it saved on the sd card?

Best regards, Ralf

**Comment by martignoni** [comment]
Hi Ralf, May I ask you to use the [MoodleBox discussion forum](https://discuss.moodlebox.net/) to ask support questions? I'd like to keep Github issues for development issues.

Sorry I didn't have the time to make a real announcement about the new forum yet.
