### ISSUE TITLE
php not 64 bits

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodlebox#115]
Hi Nicolas,
when I updated the MoodleBox to Moodle 3.6.1+ (20181210) I got the information that php is not 64 bit software. "It has been detected that your site is not using a 64-bit PHP version. It is recommended that you upgrade your site to ensure future compatibility."

Is this a problem for the MoodleBox?

Best regards, Ralf

**Comment by martignoni** [comment]
Hi Ralf,
Can you please use the discussions forum for such questions? I'd like to keep Github only for issues.
TIA
Nicolas

**Comment by ralf-krause** [comment]
Hi Nicolas,
I thought it Couleur be a problem for Moodle
Ralf

**Comment by martignoni** [comment]
Son't worry, no problem.
