### ISSUE TITLE
Maximum User Number

### ISSUE THREAD

**Issue by bicyclem** [moodlebox/moodlebox#130]
Hello! Im a moodlebox user/teacher working mostly in very poor countries teaching digital skills. I use modules such as quizes and surveys and what I've noticed is that if I have a group of 9 people doing either of these activities, people start getting kicked off or unable to access moodlebox. My experience shows me that around 8 people using moodlebox simultaneously is when problems happen. 

Does this match other people's experience? 

Is there a setting I should be aware of that would possibly improve the capacity of the moodlebox to have more than 8 people taking a quiz or otherwise using the database?

**Comment by martignoni** [comment]
Hi, please don't use this space for support question. Use the [MoodleBox forum](https://discuss.moodlebox.net/). You'll see[ there that power supply is an issue](https://discuss.moodlebox.net/d/36-low-number-of-concurrent-connected-users/20).
