### ISSUE TITLE
Spurious loop squash deprecation warning

### ISSUE THREAD

**Issue by marmur76** [moodlebox/moodlebox#131]
Our ansible config has "squash_actions = False" set.  Yet we still get a deprecation warning about squash actions.  The deprecation warning should only display if it is relevant.

**Comment by martignoni** [comment]
Please give more context. Indicate the **complete** and **precise** steps leading to the problem.

**Comment by marmur76** [comment]
Very sorry, I created this ticket in the wrong project. Please disregard
