### ISSUE TITLE
Moodle plugin installation crashes php7.3-fpm

### ISSUE THREAD

**Issue by martignoni** [moodlebox/moodlebox#142]
When installing Moodle plugins, php7.3-fpm sometimes crashes.

## Steps to reproduce

1. Install Moodle plugin
2. At the end of the installation, after database upgrade is completed, click on "Continue"

## Result
An error is displayed in the browser:

502 Bad Gateway
nginx/1.14.2

## Expected behaviour
No error is displayed

## Context info
Has occurred on models: 3B, 3B+, 4B (1GB), 4B (2GB).

Error in `/var/log/php7.3-fpm.log`:
```
[13-Jul-2019 22:10:21] WARNING: [pool www] child 11138 exited on signal 11 (SIGSEGV) after 25.652735 seconds from start
```

Error in `/var/log/nginx/error.log`:
```
2019/07/13 22:10:21 [error] 10963#10963: *276 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.0.0.213, server: moodlebox, request: "GET /admin/upgradesettings.php? HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "moodlebox.home", referrer: "http://moodlebox.home/admin/index.php?cache=0&confirmplugincheck=1"
```

Error in `/var/log/nginx/access.log`:
```
10.0.0.213 - - [13/Jul/2019:22:10:21 +0200] "GET /admin/upgradesettings.php? HTTP/1.1" 502 173 "http://moodlebox.home/admin/index.php?cache=0&confirmplugincheck=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15"
```

**Comment by martignoni** [comment]
This behavior cannot be consistently reproduced.

**Comment by martignoni** [comment]
Use following shell command if you experience this.
```
sudo systemctl reload php7.3-fpm
```

**Comment by martignoni** [comment]
Reports indicate that this is independent of the RPi model: has occurred on 3B+, 4B (1GB), 4B (2GB).

**Comment by martignoni** [comment]
Maybe this: https://bugs.php.net/bug.php?id=77955

**Comment by ralf-krause** [comment]
The same problem also happened with the new MoodleBox image and a Raspberry Pi 3B (not 3B+).
I did not install a plugin. I logged in and opened the website administration properly. After this I could not open the MoodleBox plugin anymore. Yes, I reload the php7.3-fpm and then it worked.

**Comment by ralf-krause** [comment]
Today I got the same problem when I tried to change a plugin setting. 
I opened the page for the general feedback setting http://moodlebox.home/admin/settings.php?section=modsettingfeedback and set "allow full anonymous" to yes. When I saved the changes I got the problem. After reloading php7.3-fpm I got everything working again.

**Comment by ralf-krause** [comment]
Hi Nicolas,
today I updated the Raspbian to the newest version. PHP seems to be PHP 7.3.4 as it was before. But a lot of other packages were updated. After reboot I tested to install some plugins without any problem. It could be the the reason for this issue is fixed now. I was using a Raspberry Pi 4B for this test.
Ralf

Linux moodlebox 4.19.58-v7l+ #1245 SMP Fri Jul 12 17:31:45 BST 2019 armv7l

**Comment by martignoni** [comment]
Thanks for the report. Same here, unable to reproduce since about 2016-07-15.

Let's however keep this open for some days, to be sure that this is gone.

**Comment by martignoni** [comment]
Seems to occur from time to time even with 2019-09-26 Raspbian release.

**Comment by artyuum** [comment]
Same on WSL (php7.3-fpm).

**Comment by martignoni** [comment]
Hopefully fixed with 2020-02-05 Raspbian release? Will see...

**Comment by martignoni** [comment]
As a temporary workaround, we could add this to root `crontab`:
```
*/5 * * * * systemctl restart php7.3-fpm.service
```

**Comment by ralf-krause** [comment]
Hi Nicolas,
there is an update php7.3-cli (7.3.14-1~deb10u1) for Raspbian. I can't say if this update is already part of the 2020-02-05 Raspbian release.
Ralf

**Comment by martignoni** [comment]
Installed version is `php7.3-cli/now 7.3.11-1~deb10u1`. But what interests us here is php-fpm, i.e. `php7.3-fpm/now 7.3.11-1~deb10u1`.

**Comment by ralf-krause** [comment]
Looking at http://moodlebox.home/admin/phpinfo.php I get the same version `PHP Version 7.3.14-1~deb10u1`.

**Comment by martignoni** [comment]
This is because you updated your installation. I've done it too and get the same as you.

**Comment by ralf-krause** [comment]
Could you see if this issue is repaired in Raspberry Pi OS 64 bit?

**Comment by martignoni** [comment]
This will have to wait a release of RPi OS 64bits **lite**, or at least a Release Candidate. Anyway, I'm carefully monitoring this.

**Comment by martignoni** [comment]
This indicates another workaround: https://kadai.com.mx/sigsegv-en-php-7-3-soluciones-al-problema/.

**Comment by martignoni** [comment]
PHP configuration is not optimal and leads to these PHP outages. Tweaking PHP settings fixes the problem.
