### ISSUE TITLE
Build MoodleBox based on Raspberry Pi OS 64 bit

### ISSUE THREAD

**Issue by martignoni** [moodlebox/moodlebox#171]
Raspberry Pi OS 64 bit was just announced: https://www.raspberrypi.org/forums/viewtopic.php?f=117&t=275370.

Let's try to use it for the MoodleBox!

**Comment by martignoni** [comment]
Just tested Raspberry Pi OS 64 bit image.

It works well 😄!

**Comment by martignoni** [comment]
RPI OS 64 bits Lite image was released shortly: https://downloads.raspberrypi.org/raspios_lite_arm64/images/.

**Comment by martignoni** [comment]
Will be integrated when out of beta.

**Comment by martignoni** [comment]
[New version of Raspberry Pi OS Lite 64 bit released](https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-04-09/).

**Comment by v3ss0n** [comment]
Currently it is 32bit? Any updates on going 64 bit?

**Comment by martignoni** [comment]
See https://discuss.moodlebox.net/d/260-plans-for-moodlebox-bullseye-and-64-bit/.

**Comment by martignoni** [comment]
Raspberry Pi OS with Debian Bullseye released is only 32bit. We won't release a 64bit version of MoodleBox until Raspberry Pi OS64bit is officially released.

**Comment by v3ss0n** [comment]
That make sense , i was trying to run  MoodleBox on qemu with  64bit ARM RPI4 emulation

**Comment by martignoni** [comment]
Raspberry Pi OS 64-bit is now out of beta 😄 !

**Comment by martignoni** [comment]
Works as expecting. Closing.
