### ISSUE TITLE
Update to Adminer 4.7.7

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodlebox#178]
Hi Nicolas,
what do you think about an update for Adminer 4.7.7
https://github.com/vrana/adminer/releases
Ralf

**Comment by martignoni** [comment]
With any MoodleBox image, Adminer is always installed to its latest version. See https://github.com/moodlebox/moodlebox/blob/fbe8d000137d184c74e321637ae7b9a37f99a076/roles/moodle/tasks/main.yml#L51-L57.

E.g. current test version has Adminer 4.7.7.

Thanks anyway for the heads up!
