### ISSUE TITLE
Test Raspberry Pi OS with Debian Bullseye on its release

### ISSUE THREAD

**Issue by martignoni** [moodlebox/moodlebox#213]
Debian Bullseye's release is [scheduled for 2021-08-14](https://release.debian.org/) ([see also here](https://lists.debian.org/debian-release/2021/07/msg00669.html)). 

Let's test Raspberry Pi OS as soon as it is released with Debian Bullseye.

Refs:
- https://github.com/iiab/iiab/issues/2820

**Comment by ralf-krause** [comment]
I'm looking forward to the new Raspberry Pi OS with Debian Bullseye. Will this Raspberry Pi OS automatically work with 64bit? Will it use php with 64bit? Do you have a MoodleBox test image with Debian Bullseye?

**Comment by martignoni** [comment]
Me too. All this depends on the official Raspberry OS images.

**Comment by martignoni** [comment]
Updates needed to be managed manually:
- php 7.3 -> php 7.4
- mariadb 10.3 -> 10.5

**Comment by martignoni** [comment]
TODO: check every modified configuration file for potential change in default values.

E.g. dnsmasq, nginx, mariadb, php, etc.

**Comment by martignoni** [comment]
Preliminary version seems to work correctly :-D

**Comment by martignoni** [comment]
Build on [branch `WIP-213-master_bullseye`](https://github.com/moodlebox/moodlebox/tree/WIP-213-master_bullseye) works correctly on bullseye (updated from buster).

**Comment by martignoni** [comment]
Test image available here: https://moodlebox.net/moodlebox-bullseye-test.img.bz2.

**Comment by martignoni** [comment]
Test successful! Closing. Follow up on #210.
