### ISSUE TITLE
Text logo looks bad in console

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodlebox#251]
When you start your MoodleBox with a direct access the Raspberry image looks bad. (see screenshot 1)
I would say that the image is shown in a flat colour version.
Perhaps the image uses colours which are not allowed in terminal.
I can see the four raspberry symbols at the top of the monitor when the Raspberry Pi starts up.

Yes, I can see the correct image when I connect via ssh from my iMac. (see screenshot 2)

For my iPhone and the app Termius the terminal image seems to be too big. (see screenshot 3)

### To Reproduce
Start your MoodleBox with a Monitor connected

### Additional context
- Raspberry Pi 4B
- MoodleBox version 4.3.0
- MoodleBox plugin version 2.13.0
- Monitor iiyama Prolite 1904S

### Screenshots
![moodlebox-direct-access](https://user-images.githubusercontent.com/27956839/182823822-50ff272d-51bc-4802-9f19-0cfa2eeeeb78.jpg)

<img width="718" alt="moodlebox-imac-terminal" src="https://user-images.githubusercontent.com/27956839/182829228-f279553b-3ec5-499f-b92b-5429ac5b9826.png">

![moodlebox-iphone-termius](https://user-images.githubusercontent.com/27956839/182829062-2385979a-1989-4bbe-bff7-1b4e2b12bbdb.PNG)

**Comment by ralf-krause** [comment]
I installed the MoodleBox image 4.1.0 on a new microSD because the terminal graphic was changed on Jan 11th, 2022. This was a few days after 4.1.0 was released. So with MoodleBox 4.1.0 I can show the older terminal graphic on a some devices.

Screenshots fro different devices
1 - MoodleBox with monitor iiyama ProLite P1904S
2 - iPad with the Termius app
3 - iPhone X with the Termius app

![0AAAFD1A-7024-492F-BC40-E9701E9D6295](https://user-images.githubusercontent.com/27956839/183038168-0539ea7c-0b4e-4adf-afe4-82d6da7798d6.png)

![9372FB86-7792-4A39-A051-0A7D25EAE75A](https://user-images.githubusercontent.com/27956839/183038187-ceb0b0c1-2d74-4aff-b624-c37d52c3dbca.jpeg)

![5524E309-3298-4F7A-967A-1243E4818DCB](https://user-images.githubusercontent.com/27956839/183038389-aa125466-fa6e-4657-b493-2ce712edccd2.png)

**Comment by ralf-krause** [comment]
Okay, I found that I can change the character size in the Termius app on the iPhone. 
Now I can see the correct terminal graphic without automatic line breaks but the characters are too small on the display.

![IMG_8323](https://user-images.githubusercontent.com/27956839/183046581-0b08ca39-43f1-4531-96c3-511b02d2ae90.PNG)

**Comment by martignoni** [comment]
> I installed the MoodleBox image 4.1.0 on a new microSD because the terminal graphic was changed on Jan 11th, 2022. This was a few days after 4.1.0 was released. So with MoodleBox 4.1.0 I can show the older terminal graphic on a some devices.

Screenshots with logo of current version would be useful.

**Comment by ralf-krause** [comment]
I send a lot of screenshots with the current logo. 

There are 4 screenshots in the first message of this thread #251. The first one shows the terminal image when the MoodleBox is connected to my monitor iiyama PreLite P1904S. It could be that the normal terminal console only shows 16 colours. 

The monitor seems to be okay for deeper colours because I can start the same Raspberry Pi 4B with the Raspberry Pi OS full version without any restrictions.

![](https://user-images.githubusercontent.com/27956839/182823822-50ff272d-51bc-4802-9f19-0cfa2eeeeb78.jpg)

**Comment by martignoni** [comment]
Thanks for the confirmation that the problem occurs in console. I'll have a look to see if it depends on the monitor.

**Comment by ralf-krause** [comment]
Could it be that it's a setting in the /boot/config.txt?
The HDMI cable is connected with a DVI-to-HDMI-Adapter.

**Comment by martignoni** [comment]
Finally I got my hands on a monitor. Confirming the problem.
