### ISSUE TITLE
MoodleBox version in /boot/moodlebox.txt

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodlebox#256]
It would be useful if we could see the MoodleBox version in a file on the /boot partition.

We can't find the MoodleBox version without a Raspberry Pi. If you take a microSD card for the Raspberry Pi you only can read the /boot partition when you put it into a card reader in a mac or windows computer. On my own MoodleBox cards I save a file /boot/moodlebox.txt with the MoodleBox version. So I do not need to put the card into the Raspberry Pi and start the MoodleBox to see the correct version string.

**Comment by martignoni** [comment]
Good idea, thanks.

**Comment by martignoni** [comment]
Related issue: #257.

**Comment by ralf-krause** [comment]
Great! Thanks!
