### ISSUE TITLE
Install a cloning program

### ISSUE THREAD

**Issue by martignoni** [moodlebox/moodlebox#259]
See https://discuss.moodlebox.net/d/312-install-a-cloning-program-into-the-moodlebox.

Possible candidates:
- [rpi-clone](https://github.com/billw2/rpi-clone)
- [Image File Utilities](https://forums.raspberrypi.com/viewtopic.php?t=332000)
- [sdm](https://github.com/gitbls/sdm)
- Others?

**Comment by ralf-krause** [comment]
Has the "Raspberry Pi SD Card Copier" a terminal part which runs without the GUI? Yesterday I just copied a running sd card with 64 GB to a sd card with 32 GB. Yes, it worked fine!

**Comment by martignoni** [comment]
> Has the "Raspberry Pi SD Card Copier" a terminal part which runs without the GUI?

Raspberry Pi Imager (if this is what you mean) has a CLI, but its installation forces a lot of useless GUI things, weighting about 313 MB. That's to much.

**Comment by ralf-krause** [comment]
No, I do not mean the Raspberry Pi Imager. 

There is also a program which has the name "SD card copier". This program can copy the running sd card to an usb card reader, to an usb stick or an usb ssd. It is also possible to copy a running sd card with 64 GB on an usb card reader wit a smaller sd card with 16 GB.

**Comment by martignoni** [comment]
> There is also a program which has the name "SD card copier".

Ok, found the source is here: https://github.com/raspberrypi-ui/piclone, but it's even worst: around 552 MB (and it is GUI only).

**Comment by martignoni** [comment]
[rpi-clone](https://github.com/billw2/rpi-clone) works correctly and is very light. It will be integrated into the next MoodleBox image.

**Comment by martignoni** [comment]
This works ok. Closing.
