### ISSUE TITLE
Error when updating to Moodle 4.0.4+ (20221108)

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodlebox#273]
I got an error when I updated up to Moodle 4.0.4+ (20221108).

`Coding error detected, it must be fixed by a programmer: Cannot set custom filetypes because they are defined in config.php`

I think that the error is specific for the MoodleBox. I updated two other platforms to the same Moodle version. On my MoodleBox it is not possible to open the web administration.

After I set the parameter customfiletypes to xcustomfiletypes I can open the web administration again. Yes, I know that it does not make sense to change a parameter name. I did this to find a solution for this problem.
```
$CFG->xcustomfiletypes = array(
  (object)array(
    'extension' => 'crt',
    'icon' => 'sourcecode',
    'type' => 'application/x-x509-ca-cert',
    'customdescription' => 'X.509 CA certificate'
  )
);
```

Ralf

**Comment by martignoni** [comment]
This is very annoying. I've to investigate why the update process has to set custom file types.

**Comment by ralf-krause** [comment]
Thanks for your answer!
I created an issue in the Moodle tracker https://tracker.moodle.org/browse/MDL-76247

**Comment by abias** [comment]
Hi all,

in the end, this issue turned out to be a bug in theme_boost_union which @ralf-krause uses in his moodlebox.
The bug and the fix is explained on https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/133.

This issue here can be closed then.

**Comment by martignoni** [comment]
Thanks.

**Comment by ralf-krause** [comment]
I just upgraded the plugin Boost Union on my MoodleBox. The MoodleBox runs fine again.
