### ISSUE TITLE
Update GPU memory setting to current spec 

### ISSUE THREAD

**Issue by martignoni** [moodlebox/moodlebox#321]
GPU memory setting has changed as of latest Raspberry OS version. See the [official doc](https://www.raspberrypi.com/documentation/computers/legacy_config_txt.html#gpu_mem).

**Comment by ralf-krause** [comment]
Does the MoodleBox need any GPU memory or should the setting get a minimum memory. The GPU memory seems to be part of the normal RAM so minimizing GPU should leave more RAM for other processes. Correct?

**Comment by martignoni** [comment]
The GPU mem should be minimal (we use almost no any graphic power).

But in recent version of RPiOS, this setting is not used anymore, and I'll drop it probably.

**Comment by ralf-krause** [comment]
Does the current RaspberryPiOS genarally use no GPU memory size or only for Raspberry Pi 5?

**Comment by martignoni** [comment]
See the [official doc](https://www.raspberrypi.com/documentation/computers/legacy_config_txt.html#gpu_mem), which is not very specific about this. That's why I'll probably won't change anything: if it ain't broken, don't fix it.

**Comment by ralf-krause** [comment]
As I understand the official doc the Raspberry Pi does not allocate  any GPU memory by the os. For all other Raspberry Pi models the config parameter gpu_mem is used for setup. "To ensure the best performance of Linux, you should set gpu_mem to the lowest possible value." Could the lowest value be zero?

**Comment by martignoni** [comment]
Anyway, second to the [official doc](https://www.raspberrypi.com/documentation/computers/legacy_config_txt.html#gpu_mem), gpu_mem setting is obsolete and seems to be useful only for legacy kernels.

**Comment by martignoni** [comment]
As comment https://github.com/moodlebox/moodlebox/issues/321#issuecomment-1962520904, not needed.
