### ISSUE TITLE
MoodleBox PHP timezone and OS timezone are not consistent

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodlebox#324]
The first time I saw the problem was when I setup the MoodleBox 4.6.0 to use an RTC. 
Please look at https://discuss.moodlebox.net/d/247-using-a-real-time-clock-module-on-moodlebox/8
The date/time string in the MoodleBox dashboard is different to the computer time. Yes, I thought there could be a problem with my RTC settings.

Today I did a new test. I installed a fresh microSD card with the MoodleBox 4.6.0 image. I started the MoodleBox with the new image. The MoodleBox was connected to the router so the date/time string should be correct. Yes, the date/time string in the dashboard is different to the computer time again. In my addional test I connected via ssh to get the system date/time from the Terminal ... the system date/time is correct but not the string in the MoodleBox dashboard.

You can see my tests in in the following screenshot. There are the computer time, the terminal, and the MoodleBox dashboard.

Ralf

![moodlebox-system-date-and-time](https://github.com/moodlebox/moodle-tool_moodlebox/assets/27956839/94cebe19-7728-46b2-bcc5-bdafd435e13a)

**Comment by martignoni** [comment]
Closing as fixed.
