### ISSUE TITLE
Replace Adminer with AdminerEvo 

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodlebox#349]
What do you think about AdminerEvo for the MoodleBox?
https://github.com/adminerevo/adminerevo

Adminer is a very nice software but it's no maintain since 3 years. AdminerEvo is using the sources of Adminer. The current version of the Moodle plugin Adminer https://moodle.org/plugins/local_adminer also uses AdminerEvo.

**Comment by martignoni** [comment]
Thanks, I didn't know about his maintained fork of Adminer. Investigating now.

**Comment by martignoni** [comment]
Download URL: https://download.adminerevo.org/latest/adminer/adminer.zip

**Comment by martignoni** [comment]
Direct download from Github (for 4.8.4 version): https://github.com/adminerevo/adminerevo/releases/download/v4.8.4/adminer-4.8.4.php

**Comment by ralf-krause** [comment]
Thanks! This Adminer version works fin with PHP 8.1, 8.2 and 8.3.
