### ISSUE TITLE
Update image based on Raspbian Lite 2018-03-13

### ISSUE THREAD

**Issue by martignoni** [moodlebox/moodlebox#63]
See http://downloads.raspberrypi.org/raspbian/release_notes.txt

**Comment by martignoni** [comment]
Just tested with latest image. Everything is working.

**Comment by ralf-krause** [comment]
Hi Nicolas, 
to have the old wifi with 2.4 GHz and 802.11n modus there is no problem with the new Raspberry Pi 3B+. I updated the Raspbian OS up to 4.9.80-v7+ #1098 and now I can communicate with 2.4 GHz. 
Ralf

**Comment by martignoni** [comment]
Ralf, thanks for this feedback.

**Comment by martignoni** [comment]
All done, closing.
