### ISSUE TITLE
Update Moodle to version 3.4.2

### ISSUE THREAD

**Issue by martignoni** [moodlebox/moodlebox#64]
Update next version to Moodle 3.4.2.

**Comment by martignoni** [comment]
All done. Closing.

**Comment by ralf-krause** [comment]
Hallo Nicolas,
auf der Seite https://moodlebox.net/de/help/disk-image-herunterladen/ wird noch auf Moodle 3.4.1+ hingewiesen, nicht auf die aktuelle Version 3.4.2. Ich habe es nicht getestet, aber die ch gehe davon aus, dass das Image 3.4.2 enthält und nur die Beschreibung falsch ist.
Gruß Ralf

**Comment by martignoni** [comment]
Danke Ralf, ist jetzt auf die Webseite korrigiert.
