### ISSUE TITLE
Update Raspbian 4.14.50-v7+ #1122

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodlebox#78]
Hi Nicolas,
I updated my MoodleBox to Raspbian 4.14.50.
`Linux moodlebox -v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l`

Everything seems to be okay with the MoodleBox.
Ralf

![moodlebox-1](https://user-images.githubusercontent.com/27956839/42086351-160bc462-7b93-11e8-8e77-460f8af43dff.png)
![moodlebox-2](https://user-images.githubusercontent.com/27956839/42086360-1cba6c64-7b93-11e8-865b-97371caf0811.png)

**Comment by martignoni** [comment]
Thanks. Precisely: did you do a kernel update?

**Comment by ralf-krause** [comment]
My MoodleBox uses the image MoodleBox 2.4.0 and I made a Raspbian update. 
`sudo apt-get update && sudo apt-get upgrade -y`

**Comment by martignoni** [comment]
Thanks for the info. It's a kernel update.

I'll close this and open a new issue about upgrading to the next Raspbian image (but after the MoodleMoot! Too much work now :-)).

**Comment by martignoni** [comment]
See #79.
